### ISSUE TITLE
Improvement: Instructions to install node-expressgen globally using yarn

### ISSUE THREAD

**Issue by gunvantsr** [gunvantsr/expressgen#3]
Hello 👋

Currently, in our [Installation](https://github.com/gunvantsr/expressgen#installation) docs part, we only have the npm command to install **expressgen** globally. 

![image](https://user-images.githubusercontent.com/14096299/181290769-dca7124d-a88c-4ceb-b423-2f6afd6620b5.png)

It will be helpful to have an alternative for doing the same using yarn. 

Please refer to  [CONTRIBUTING.md](https://github.com/gunvantsr/expressgen/blob/master/CONTRIBUTING.md) for setting up the project on your local machine. 

Feel free to ask for help, clarification, or doubts in the comments!

**Comment by sleekyom** [comment]
Hi @gunvantsr i can take this if it's still available

**Comment by gunvantsr** [comment]
Hello @sleekyom,

Yes, you can go ahead!

**Comment by sleekyom** [comment]
Made change and submitted a PR
